#pragma once

#define MAIN_Version "4e18ea1"
#define KNX_Version "2.2.0+4fb43ed"
#define MODULE_Common_Version "1.4.3+d0c5729"
#define MODULE_Common_Version_Major 1
#define MODULE_Common_Version_Minor 4
#define MODULE_Common_Version_Revision 3
#define MODULE_Common_ETS 20
#define MODULE_HardwareConfig_Version "1.0.0+35e6a92"
#define MODULE_HardwareConfig_Version_Major 1
#define MODULE_HardwareConfig_Version_Minor 0
#define MODULE_HardwareConfig_Version_Revision 0
#define MODULE_HardwareConfig_ETS 16
#define MODULE_LogicModule_Version "3.7.1+1ba35cb"
#define MODULE_LogicModule_Version_Major 3
#define MODULE_LogicModule_Version_Minor 7
#define MODULE_LogicModule_Version_Revision 1
#define MODULE_LogicModule_ETS 55
#define MODULE_FileTransferModule_Version "0.1.1+75e4c00"
#define MODULE_FileTransferModule_Version_Major 0
#define MODULE_FileTransferModule_Version_Minor 1
#define MODULE_FileTransferModule_Version_Revision 1
#define MODULE_FileTransferModule_ETS 1
#define MODULE_SwitchActuator_Version "0.1.0+95c285a"
#define MODULE_SwitchActuator_Version_Major 0
#define MODULE_SwitchActuator_Version_Minor 1
#define MODULE_SwitchActuator_Version_Revision 0
#define MODULE_SwitchActuator_ETS 1
